### ISSUE TITLE
The new project from the GraphQL schema is not being created.

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#1205]
**IDEA version**: IntelliJ IDEA 2023.2.5 (Ultimate Edition)
**OS**: macOS 14.1.1
**Plugin version**:
    org.jetbrains.kotlin (232-1.9.21-release-633-IJ10072.27)
    com.intellij.lang.jsgraphql (4.0.2)
    com.haulmont.amplicode (0.1.SNAPSHOT3604-232)
**Generator version**: 0.60.0

**Schema**: [schema.graphqls](https://youtrack.haulmont.com/api/files/96-26306260?sign=MTcwMjUxMjAwMDAwMHwyMS0yMjg4fDk2LTI2MzA2MjYwfFZUS1dpbksyblFTRFJUYlE4OUtJd0pR%0D%0ANEw0dkNsN2ZLLXl1Ml9VbmV0M1ENCg%0D%0A&updated=1700128262317&forceDownload=true)

**Steps**:

1. Create new folder
2. open the Amplicode extension
3. Click Initialize
4. Go through all the steps of creating a project

**AR**: Only the "generation" folder and the "package-lock.json" file were created. The error occurred when running "npm install.
**ER**: Amplicode project has been full created

**Ticket in studio:** [AST-919](https://youtrack.haulmont.com/issue/AST-919) You cannot create a frontend from a graphql schema with type void
**Ticket VSCode:** [AVSC-112](https://youtrack.haulmont.com/issue/AVSC-112) The new project from the GraphQL schema is not being created.

Я делал это действие через cli, и результат такой:
```typescript
amplicodePipeline started, generator version 0.61.0, Node.js v16.13.2
amplicodeGetGraphQLSchema: read schema list from paths '["/Users/admin/Documents/schema_test.graphqls"]'
readSchemaFile from '/Users/admin/Documents/schema_test.graphqls'
✖ An error occured while running AppGenerator#generate
Unhandled Rejection  Promise {
  <rejected> Error: Unknown type "Void". Did you mean "ID"?
  
  Unknown type "Void". Did you mean "ID"?
      at assertValidSDL (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/graphql/validation/validate.js:107:11)
      at buildASTSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/graphql/utilities/buildASTSchema.js:45:34)
      at makeExecutableSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/schema/cjs/makeExecutableSchema.js:73:47)
      at mergeSchemas (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/schema/cjs/merge-schemas.js:32:63)
      at getSchemaFromSources (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/load/cjs/schema.js:56:46)
      at loadSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/load/cjs/schema.js:19:12)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async amplicodeGetGraphQLSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@amplicode/codegen/lib/building-blocks/stages/graphql-schema/amplicodeGetGraphQLSchema.js:42:12)
      at async amplicodePipeline (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:30:20)
      at async AppGenerator.generate (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@amplicode/codegen/lib/generators/react-admin/app/index.js:21:9)
}  reason:  Error: Unknown type "Void". Did you mean "ID"?

Unknown type "Void". Did you mean "ID"?
    at assertValidSDL (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/graphql/validation/validate.js:107:11)
    at buildASTSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/graphql/utilities/buildASTSchema.js:45:34)
    at makeExecutableSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/schema/cjs/makeExecutableSchema.js:73:47)
    at mergeSchemas (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/schema/cjs/merge-schemas.js:32:63)
    at getSchemaFromSources (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/load/cjs/schema.js:56:46)
    at loadSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@graphql-tools/load/cjs/schema.js:19:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async amplicodeGetGraphQLSchema (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@amplicode/codegen/lib/building-blocks/stages/graphql-schema/amplicodeGetGraphQLSchema.js:42:12)
    at async amplicodePipeline (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:30:20)
    at async AppGenerator.generate (/Users/admin/.npm/_npx/9fe2eb162ae46ceb/node_modules/@amplicode/codegen/lib/generators/react-admin/app/index.js:21:9)
admin@Admins-MacBook-Pro untitled1 % 

```

**Comment by vadimbasko** [comment]
Looks like we should pass two schema files in cli. Schema will be divided in multiple files on backend.

**Comment by vadimbasko** [comment]
Not generator issue. In case of backend schema format changes we need to pass in generator `Unified graphql schema`, generated by Studio plugin.
