### ISSUE TITLE
Error running 'npm i' command in an existing project using 6 npm 

### ISSUE THREAD

**Issue by owlet1997** [Amplicode/amplicode-frontend#121]
**Environment:**
Ubuntu 20.04
npm 6.14.13
Intellij IDEA 2021.3 Ultimate

**TC:**
1. Clone the [project](https://github.com/jmix-projects/amplicode-deployment-demo-r2.git )
2. Open the terminal -> run the command `cd frontend` -> run the command `npm i`

**AR:**
the process has not been finished, an error occurs:
```
31580 verbose stack TypeError: Cannot read property '@graphql-typed-document-node/core' of undefined
31580 verbose stack at /usr/lib/node_modules/npm/lib/install/update-package-json.js:27:36
31580 verbose stack at Array.map (<anonymous>)
31580 verbose stack at module.exports (/usr/lib/node_modules/npm/lib/install/update-package-json.js:23:8)
31580 verbose stack at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
31580 verbose stack at ret (eval at makeNodePromisifiedEval (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:1:1), <anonymous>:13:39)
31580 verbose stack at /usr/lib/node_modules/npm/lib/install/action/refresh-package-json.js:35:14
31580 verbose stack at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
31580 verbose stack at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
31580 verbose stack at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
31580 verbose stack at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
31580 verbose stack at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
31580 verbose stack at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
31580 verbose stack at Promise._resolveCallback (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:459:14)
31580 verbose stack at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:529:17)
31580 verbose stack at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
31580 verbose stack at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
31581 verbose cwd /home/shatalova/IdeaProjects/amplicode-deployment-demo-r22/frontend
``` 
the `package-lock.json` was generated using npm 7

**Comment by ilya-trifonov** [comment]
@owlet1997  Can't reproduce error.
