### ISSUE TITLE
White screen when launching the frontend

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#1252]
**IDEA version**: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
**OS**: macOS 14.1.1
**Generator**: 0.62.2
**Project**:

**Steps**:
1. Open project
2. Start backend and frontend
3. Open localhost

**AR**: White screen is displayed, many errors in the console

 ```typescript
Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient2 (chunk-CR7HLJHO.js?v=891e3643:8400:11)
    at useLogout (chunk-CR7HLJHO.js?v=891e3643:18734:21)
    at useLogoutIfAccessDenied (chunk-CR7HLJHO.js?v=891e3643:11496:16)
    at usePermissions (chunk-CR7HLJHO.js?v=891e3643:18988:30)
    at useACL (useACL.ts:15:34)
    at App (App.tsx:26:3)
    at renderWithHooks (chunk-GYWC62UC.js?v=891e3643:12171:26)
    at mountIndeterminateComponent (chunk-GYWC62UC.js?v=891e3643:14921:21)
    at beginWork (chunk-GYWC62UC.js?v=891e3643:15902:22)
    at HTMLUnknownElement.callCallback2 (chunk-GYWC62UC.js?v=891e3643:3674:22)
```
 ```typescript
The above error occurred in the <App> component:

    at App (http://127.0.0.1:3000/src/app/App.tsx:41:37)
    at ApolloProvider (http://127.0.0.1:3000/node_modules/.vite/deps/@apollo_client.js?v=5ab2fed2:6219:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
 ```typescript
Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient2 (chunk-CR7HLJHO.js?v=891e3643:8400:11)
    at useLogout (chunk-CR7HLJHO.js?v=891e3643:18734:21)
    at useLogoutIfAccessDenied (chunk-CR7HLJHO.js?v=891e3643:11496:16)
    at usePermissions (chunk-CR7HLJHO.js?v=891e3643:18988:30)
    at useACL (useACL.ts:15:34)
    at App (App.tsx:26:3)
    at renderWithHooks (chunk-GYWC62UC.js?v=891e3643:12171:26)
    at mountIndeterminateComponent (chunk-GYWC62UC.js?v=891e3643:14921:21)
    at beginWork (chunk-GYWC62UC.js?v=891e3643:15902:22)
    at beginWork$1 (chunk-GYWC62UC.js?v=891e3643:19749:22)
```
<img width="1301" alt="Screenshot 2024-01-31 at 16 07 44" src="https://github.com/Amplicode/amplicode-frontend/assets/126795807/299ac018-b4b4-4043-b460-fc912c50f475">

This is a floating bug, occurs usually on first runs, but has also occurred several restarts in a row.

**Comment by MaslovMaximV** [comment]
This is the same reason why Intellij IDEA does not run component previews
