### ISSUE TITLE
Exception generating Entity Details screen for graphql methods with not-null parameters

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#167]
Sample project: attached
[sample.zip](https://github.com/Amplicode/amplicode-frontend/files/8025036/sample.zip)

OwnerController:
```
    @NonNull
    public OwnerDTO findById(@NonNull @Argument Long id) {
...

    @NonNull
    public OwnerDTO update(@NonNull @Argument OwnerInputDTO input) {
...
```

Generated GraphQL schema:
```
type Query {
  owner(id: BigInteger!): OwnerDTO!
...

type Mutation {
...
  update_Owner(input: OwnerInputDTOInput!): OwnerDTO!
...
```

When I try to create "Entity Details" screen for these endpoints, exception occurs:
```
2022-02-08 19:12:39,827 [2629940]   INFO - eneration.FrontGeneratorRunner - startProcess: /usr/bin/node /home/alexander/projects/asamples/petclinic-spring-graphql/frontend/generation/node_modules/@amplicode/codegen/bin/amplicodegen react-typescript:entity-details --schema /home/alexander/projects/asamples/petclinic-spring-graphql/src/main/resources/graphql/schema.graphqls --dest /home/alexander/projects/asamples/petclinic-spring-graphql/frontend/src/app/owners --answers eyJtdXRhdGlvbiI6Im11dGF0aW9uIHVwZGF0ZV9Pd25lcigkaW5wdXQ6IE93bmVySW5wdXREVE9JbnB1dCEpIHtcbiAgdXBkYXRlX093bmVyKGlucHV0OiAkaW5wdXQpIHtcbiAgICBhZGRyZXNzXG4gICAgY2l0eVxuICAgIGVtYWlsXG4gICAgZmlyc3ROYW1lXG4gICAgaWRcbiAgICBsYXN0TmFtZVxuICAgIHRlbGVwaG9uZVxuICB9XG59IiwiaWRGaWVsZCI6ImlkIiwicmVmZXRjaFF1ZXJ5TmFtZSI6Im93bmVyTGlzdCIsInF1ZXJ5IjoicXVlcnkgb3duZXIoJGlkOiBCaWdJbnRlZ2VyISkge1xuICBvd25lcihpZDogJGlkKSB7XG4gICAgYWRkcmVzc1xuICAgIGNpdHlcbiAgICBlbWFpbFxuICAgIGZpcnN0TmFtZVxuICAgIGlkXG4gICAgbGFzdE5hbWVcbiAgICB0ZWxlcGhvbmVcbiAgfVxufSIsImNvbXBvbmVudE5hbWUiOiJPd25lckRldGFpbHMiLCJzaG91bGRBZGRUb01lbnUiOmZhbHNlfQ== --dirShift ../../ 

...


08/02/2022
19:12	Error running front generator
				Skipping prompts since answers are provided
				node:events:368
				throw er; // Unhandled 'error' event
				^
				Error: Output type name not found
				at deriveGraphQLEditorModel (/home/alexander/projects/asamples/petclinic-spring-graphql/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:71:15)
				at /home/alexander/projects/asamples/petclinic-spring-graphql/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:29:221
				at Generator.next (<anonymous>)
				at /home/alexander/projects/asamples/petclinic-spring-graphql/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:8:71
				at new Promise (<anonymous>)
				at __awaiter (/home/alexander/projects/asamples/petclinic-spring-graphql/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.... (show balloon)

19:12	JPA Buddy Error
				java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to generate component
				See log file for details (/home/alexander/.cache/JetBrains/IntelliJIdea2021.3/log/idea.log)

```

If I remove all Nonnull annotations from controller & schema - the code generates and compiles successfully.

**Comment by vadimbasko** [comment]
Could not reproduce issue now. 

In this branch [vb/chore/amplicode-frontend/167](https://github.com/Amplicode/amplicode-mvp-petclinic/tree/vb/chore/amplicode-frontend/167) of amplicode petclinic I've changed 'OwnerController' as described above, and then
- re-generate owner management screen
- generate standalone owner details screens

Generation completed successfully and all generated screens works in browser. 

The only one thing that I had to do additionally - is to run re-generation TS types after schema update 
`cd frontend/ && npm run generate` - not sure how we should handle this in Studio.

And one point to be discussed. After schema change (not null constrains added), and TS types regeneration - previously generated owner management screens will not be compiled.

**Comment by alexbudarov** [comment]
> And one point to be discussed. After schema change (not null constrains added) TS types regeneration will fail in case of- previously generated owner management screens (if the screens have not been deleted) contains queries and mutations, which differs from schema.

This is very serious.

**Comment by owlet1997** [comment]
generator version 0.14.1

had the same error, project has not been compiled if the query with a non-null argument was used:
![image](https://user-images.githubusercontent.com/45730069/163113266-c230f069-c165-4aa3-8312-cb1da7b4c136.png)

the same details screen with query with a nullable argument has been compiled successfully:
![image](https://user-images.githubusercontent.com/45730069/163113441-7343d5e4-1395-4daf-a269-e616d2e19e5e.png)

the GraphQL query names are unique
[test project ](https://github.com/Amplicode/amplicode-frontend/files/8478705/amplicode-mvp-petclinic10.zip) is attached
