### ISSUE TITLE
"Output type name not found" when generating entity details

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#254]
Generator command:

```
/usr/bin/node /home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/bin/amplicodegen react-typescript:entity-details --schema /home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/src/main/resources/graphql/schema.graphqls --dest /home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/src/app --answers eyJtdXRhdGlvbiI6Im11dGF0aW9uIHVwZGF0ZV9UZXN0KCRpbnB1dDogVGVzdElucHV0RFRPSW5wdXQpIHtcbiAgdXBkYXRlX1Rlc3QoaW5wdXQ6ICRpbnB1dCkge1xuICAgIGJpZ0RlY2ltYWxcbiAgICBiaWdJbnRcbiAgICBib29sXG4gICAgYm9vbFByaW1pdGl2ZVxuICAgIGJ5dGVBcnJheVxuICAgIGJ5dGVQcmltaXRpdmVcbiAgICBieXRlUHJpbWl0aXZlQXJyYXlcbiAgICBieXRlVGVzdFxuICAgIGNhbGVuZGFyXG4gICAgY2hhckFycmF5XG4gICAgY2hhclByaW1pdGl2ZVxuICAgIGNoYXJQcmltaXRpdmVBcnJheVxuICAgIGNoYXJhY3RlclxuICAgIGN1cnJlbmN5XG4gICAgZGF0ZVxuICAgIGRhdGVVdGlsXG4gICAgZG91YmxlVGVzdFxuICAgIGR1cmF0aW9uXG4gICAgZmxvYXRUZXN0XG4gICAgaWRcbiAgICBpbnN0YW50XG4gICAgaW50VGVzdFxuICAgIGxvY2FsRGF0ZVxuICAgIGxvY2FsRGF0ZVRpbWVcbiAgICBsb2NhbFRpbWVcbiAgICBsb2NhbGVcbiAgICBsb25nVGVzdFxuICAgIG9mZnNldERhdGVUaW1lXG4gICAgb2Zmc2V0VGltZVxuICAgIHNob3J0UHJpbWl0aXZlXG4gICAgc2hvcnRUZXN0XG4gICAgc3RyaW5nXG4gICAgdGltZVxuICAgIHRpbWVTdGFtcFxuICAgIHVybFxuICAgIHV1aWRUZXN0XG4gICAgem9uZWREYXRlVGltZVxuICB9XG59IiwiaWRGaWVsZCI6ImlkIiwicmVmZXRjaFF1ZXJ5TmFtZSI6IkRldGFpbHMyMjIiLCJxdWVyeSI6InF1ZXJ5IHRlc3RMaXN0IHtcbiAgdGVzdExpc3Qge1xuICAgIGJpZ0RlY2ltYWxcbiAgICBiaWdJbnRcbiAgICBib29sXG4gICAgYm9vbFByaW1pdGl2ZVxuICAgIGJ5dGVBcnJheVxuICAgIGJ5dGVQcmltaXRpdmVcbiAgICBieXRlUHJpbWl0aXZlQXJyYXlcbiAgICBieXRlVGVzdFxuICAgIGNhbGVuZGFyXG4gICAgY2hhckFycmF5XG4gICAgY2hhclByaW1pdGl2ZVxuICAgIGNoYXJQcmltaXRpdmVBcnJheVxuICAgIGNoYXJhY3RlclxuICAgIGN1cnJlbmN5XG4gICAgZGF0ZVxuICAgIGRhdGVVdGlsXG4gICAgZG91YmxlVGVzdFxuICAgIGR1cmF0aW9uXG4gICAgZmxvYXRUZXN0XG4gICAgaWRcbiAgICBpbnN0YW50XG4gICAgaW50VGVzdFxuICAgIGxvY2FsRGF0ZVxuICAgIGxvY2FsRGF0ZVRpbWVcbiAgICBsb2NhbFRpbWVcbiAgICBsb2NhbGVcbiAgICBsb25nVGVzdFxuICAgIG9mZnNldERhdGVUaW1lXG4gICAgb2Zmc2V0VGltZVxuICAgIHNob3J0UHJpbWl0aXZlXG4gICAgc2hvcnRUZXN0XG4gICAgc3RyaW5nXG4gICAgdGltZVxuICAgIHRpbWVTdGFtcFxuICAgIHVybFxuICAgIHV1aWRUZXN0XG4gICAgem9uZWREYXRlVGltZVxuICB9XG59IiwiY29tcG9uZW50TmFtZSI6IkRldGFpbHMyMjIiLCJzaG91bGRBZGRUb01lbnUiOmZhbHNlfQ== --dirShift ../
```

Result:

```
throw er; // Unhandled 'error' event
^



Error: Output type name not found
at deriveGraphQLEditorModel (/home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:75:15)
at /home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:30:221
at Generator.next (<anonymous>)
at /home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:8:71
at new Promise (<anonymous>)
at __awaiter (/home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:4:12)
at deriveEntityDetailsTemplateModel (/home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:24:72)
at Object.<anonymous> (/home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:37:37)
at Generator.next (<anonymous>)
at fulfilled (/home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:5:58)
Emitted 'error' event on MvpEntityEditor instance at:
at Immediate.<anonymous> (/home/dmitry/IdeaProjects/amplicode-mvp-petclinic_final/frontend/generation/node_modules/yeoman-generator/lib/index.js:1022:20)
at processImmediate (node:internal/timers:466:21)

Environment:
Ubuntu 20.04 LTS (PopOS)
Node v16.14.2
NPM 7.24.2
```

**Comment by vyacheslav-pushkin** [comment]
We don't support npm 7
