### ISSUE TITLE
Frontend auth config -  Form Login

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#420]

**Comment by alexbudarov** [comment]
Generator fails for me:

node:events:368 throw er; // Unhandled 'error' event ^ ReferenceError: /home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/auth-form-login/template/src/core/security/login/Login.tsx:68 66|
67|
>> 68|
%= appTitle %>
69|
70|   71|  budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/auth-form-login/template/src/core/security/login/Login.tsx":12:26) at Login (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/ejs/lib/ejs.js:703:17) at Object.exports.render (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/ejs/lib/ejs.js:425:37) at render (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:13:18) at process (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:35:16) at applyProcessingFunc (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/mem-fs-editor/lib/actions/copy.js:13:16) at EditionInterface.exports._copySingle (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/mem-fs-editor/lib/actions/copy.js:65:16) at /home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/mem-fs-editor/lib/actions/copy.js:52:10 at Array.forEach ( ) at EditionInterface.exports.copy (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/mem-fs-editor/lib/actions/copy.js:51:9) Emitted 'error' event on AuthFormLogin instance at: at Immediate.  (/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/yeoman-generator/lib/index.js:1022:20) at processImmediate (node:internal/timers:464:21) { path: '/home/budarov/projects/asamples/statefuloauth/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/auth-form-login/template/src/core/security/login/Login.tsx' }


Needing "appTitle" variable seems logical - it is used on the login screen.
