### ISSUE TITLE
Error in generator when creating front component

### ISSUE THREAD

**Issue by andreysubbotin** [Amplicode/amplicode-frontend#474]
Petclinic sample.
Try to generate entity management for `PetType`. 
Error occurs:
```
Skipping prompts since answers are provided node:events:505 throw er; // Unhandled 'error' event ^ TypeError: Cannot read properties of undefined (reading 'replace') at Object.splitByCapitalLetter (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/lib/common/utils.js:29:45) at Object.deriveScreenTemplateModel (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/stages/template-model/pieces/amplicode/ScreenTemplateModel.js:12:26) at Object.deriveEntityDetailsTemplateModel (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:24:34) at deriveManagementTemplateModel (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-management/template-model.js:17:63) at Object.amplicodePipeline (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:26:33) at async ReactEntityManagementGenerator.generate (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-management/index.js:21:9) Emitted 'error' event on ReactEntityManagementGenerator instance at: at Immediate.  (/Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/yeoman-generator/lib/index.js:1022:20) at processImmediate (node:internal/timers:466:21)
```

Command:
```
bash -c /usr/local/opt/node@16/bin/node /Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/generation/node_modules/@amplicode/codegen/bin/amplicodegen react-typescript:entity-management --schema /Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/src/main/resources/graphql/schema.graphqls --dest /Users/subbotin/Developer/work/samples/amplicode-mvp-petclinic/frontend/src/app/screens/management --answers eyJtb2RlIjoiZWRpdCIsImRldGFpbHNDb21wb25lbnROYW1lIjoiUGV0VHlwZURldGFpbHMiLCJsaXN0SWRGaWVsZCI6ImlkIiwidXBzZXJ0TXV0YXRpb24iOiJtdXRhdGlvbiBVcGRhdGVQZXRUeXBlX1BldFR5cGVMaXN0KCRpbnB1dDogUGV0VHlwZUlucHV0RFRPKSB7XG4gIHVwZGF0ZVBldFR5cGUoaW5wdXQ6ICRpbnB1dCkge1xuICAgIGRlZmVuc2VTdGF0dXNcbiAgICBpZFxuICAgIG5hbWVcbiAgfVxufSIsImxpc3RDb21wb25lbnROYW1lIjoiUGV0VHlwZUxpc3QiLCJkZXRhaWxzSWRGaWVsZCI6ImlkIiwic2hvdWxkQWRkVG9NZW51Ijp0cnVlLCJkZXRhaWxzUXVlcnkiOiJxdWVyeSBQZXRUeXBlX1BldFR5cGVMaXN0KCRpZDogSUQpIHtcbiAgcGV0VHlwZShpZDogJGlkKSB7XG4gICAgZGVmZW5zZVN0YXR1c1xuICAgIGlkXG4gICAgbmFtZVxuICB9XG59IiwiZGVsZXRlTXV0YXRpb24iOiJtdXRhdGlvbiBEZWxldGVQZXRUeXBlX1BldFR5cGVMaXN0KCRpZDogSUQhKSB7XG4gIGRlbGV0ZVBldFR5cGUoaWQ6ICRpZCkgXG59IiwibGlzdFF1ZXJ5IjoicXVlcnkgUGV0VHlwZUxpc3RfUGV0VHlwZUxpc3Qge1xuICBwZXRUeXBlTGlzdCB7XG4gICAgZGVmZW5zZVN0YXR1c1xuICAgIGlkXG4gICAgbmFtZVxuICB9XG59In0= --dirShift ../../../
```

**Comment by vyacheslav-pushkin** [comment]
Caused by generator version mismatch. See https://youtrack.haulmont.com/issue/AST-336.
