### ISSUE TITLE
Screen creation error caused by GraphQL conroller 

### ISSUE THREAD

**Issue by TikhomirovME** [Amplicode/amplicode-frontend#509]
IntelliJ IDEA 2022.1.3 (Ultimate Edition)
Build #IU-221.5921.22, built on June 21, 2022
Licensed to Общество с ограниченной ответственностью "Хоулмонт Самара" / Denis Kulikov
You have a perpetual fallback license for this version.
Subscription is active until November 3, 2022.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 8
Non-Bundled Plugins:
org.intellij.plugins.hcl (221.5921.12)
com.intellij.lang.jsgraphql (3.1.4)
com.haulmont.amplicode (0.1.SNAPSHOT1256-221)
Kotlin: 221-1.6.21-release-337-IJ5921.22
npm 8.1.2
Node 16.13.1

**Steps**
Open petclinic project  ([https://github.com/Amplicode/amplicode-mvp-petclinic](https://github.com/Amplicode/amplicode-mvp-petclinic))
Remove GraphQL controller and entity screens.
Create a new graphics controller for the entity.
Create screens for the entity.

Alternative playback path

Create a new amplicode project
Add frontend module (generator 0.23.0)
Create an entity
Create a repository
Create GraphQL controller
Create a screen for an entity

AR
```
Error: Fields from topField aren't found
    at Object.getSelectedFieldNamesFromTopField (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/stages/template-model/pieces/graphql-utils/getSelectedFieldNamesFromTopField.js:13:15)
    at Object.getEntityAttributes (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/stages/template-model/pieces/graphql-utils/getEntityAttributes.js:18:68)
    at deriveGraphQLEditorModel (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:41:58)
    at deriveEntityDetailsTemplateModel (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/template-model.js:25:12)
    at Object.amplicodePipeline (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:26:33)
    at async MvpEntityEditor.generate (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-details/index.js:21:9)
Emitted 'error' event on MvpEntityEditor instance at:
    at Immediate.<anonymous> (/home/kozubav/IdeaProjects/untitled/frontend/generation/node_modules/yeoman-generator/lib/index.js:1022:20)
    at processImmediate (node:internal/timers:464:21)
```
[untitled15.zip](https://github.com/Amplicode/amplicode-frontend/files/9067389/untitled15.zip)

ps the GraphQL controller created by default in petclinic does not cause an error.

**Comment by HegelPro** [comment]
The bug didn't reproduce with this error message. It's reproducing with the same error message from Problem 1 - #490
