### ISSUE TITLE
Exception generating Entity List screen for unusual GraphQL schema

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#510]
Generator: 0.23.0
Project:
[spacestrakh1.zip](https://github.com/Amplicode/amplicode-frontend/files/9070105/spacestrakh1.zip)
 
Data model in GraphQL schema is determined by imported external SpaceX web service.

New -> Frontend Component -> Entity List.
Query to load items = launchList
Choose fields: id, mission_name
Delete mutation = not set

Generation error occurs:

2022-07-08 12:01:34,204 [4105565]   INFO - #c.h.a.f.g.FrontGeneratorRunner - startProcess: bash -c /usr/bin/node /home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/@amplicode/codegen/bin/amplicodegen react-typescript:entity-list --schema /home/budarov/projects/ajunk/spacestrakh1/src/main/resources/graphql/schema.graphqls --dest /home/budarov/projects/ajunk/spacestrakh1/frontend/src/app/screens/launches --answers eyJtb2RlIjoiZWRpdCIsImlkRmllbGQiOiJpZCIsInJvdXRlIjoibGF1bmNoLWxpc3QiLCJxdWVyeSI6InF1ZXJ5IExhdW5jaExpc3RfTGF1bmNoTGlzdChcbiAgJGxhdW5jaFllYXI6IFN0cmluZ1xuICAkcm9ja2V0TmFtZTogU3RyaW5nXG4pIHtcbiAgbGF1bmNoTGlzdChcbiAgICBsYXVuY2hZZWFyOiAkbGF1bmNoWWVhclxuICAgIHJvY2tldE5hbWU6ICRyb2NrZXROYW1lXG4gICkge1xuICAgIGlkXG4gICAgbWlzc2lvbl9uYW1lXG4gIH1cbn0iLCJjb21wb25lbnROYW1lIjoiTGF1bmNoTGlzdCIsInNob3VsZEFkZFRvTWVudSI6dHJ1ZSwidHlwZSI6ImNhcmRzIn0= --dirShift ../../../

Skipping prompts since answers are provided node:events:368 throw er; // Unhandled 'error' event ^ TypeError: Cannot use 'in' operator to search for 'getFields' in undefined at Object.getTypeFields (/home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/stages/template-model/pieces/graphql-utils/getTypeFields.js:6:23) at Object.getEntityAttributes (/home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/stages/template-model/pieces/graphql-utils/getEntityAttributes.js:17:40) at deriveEntityListTemplateModel (/home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-list/template-model.js:29:46) at Object.amplicodePipeline (/home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/@amplicode/codegen/lib/building-blocks/pipelines/amplicodePipeline.js:26:33) at async EntityListGenerator.generate (/home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/@amplicode/codegen/lib/generators/react-typescript/entity-list/index.js:21:9) Emitted 'error' event on EntityListGenerator instance at: at Immediate.  (/home/budarov/projects/ajunk/spacestrakh1/frontend/generation/node_modules/yeoman-generator/lib/index.js:1022:20) at processImmediate (node:internal/timers:464:21)

**Comment by alexbudarov** [comment]
it was the same as problem with notnull types: #490

**Comment by HegelPro** [comment]
Different error messages with #490 ticket

**Comment by vyacheslav-pushkin** [comment]
fixed in 0.26.0
