### ISSUE TITLE
Generation failed on linux

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#797]
Running a command from a frontend/generation folder: 
`npx amplicodegen react-admin:app "--dest" '/home/userubuntu/userproj/frontend' "--schema" '/home/userubuntu/userproj/src/main/resources/graphql/schema.graphqls' "--answers" 'eyJhcHBUaXRsZSI6ImFwcCIsImFwcFNob3J0TmFtZSI6ImFwcCIsInBvcnROdW1iZXIiOiI4MDgwIiwiZ3JhcGhxbFVyaSI6Ii9ncmFwaHFsIn0='`

Error:
```
Error: ENOENT: no such file or directory, scandir '/home/userubuntu/userproj/frontend/_gitignore'
    at Object.readdirSync (node:fs:1452:3)
    at exports.readdir (/home/userubuntu/userproj/frontend/generation/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (//home/userubuntu/userproj/frontend/generation/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/home/userubuntu/userproj/frontend/generation/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (//home/userubuntu/userproj/frontend/generation/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:12)
    at readdirSync (//home/userubuntu/userproj/frontend/generation/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/home/userubuntu/userproj/frontend/generation/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/home/userubuntu/userproj/frontend/generation/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/home/userubuntu/userproj/frontend/generation/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/userubuntu/userproj/frontend/_gitignore'
}
```

**Comment by vadimbasko** [comment]
@MaslovMaximV  looks like this reproduced only on node version > 16.x 
At this momenent only node version 16.x is supported. Please, check installed node version.
